name: sofi
description: "A social media platform to share your incredible stories to your friend"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  http: ^1.3.0
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  provider: ^6.1.4
  intl: ^0.19.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.1
  location: ^7.0.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
